
---
- hosts: all
  become: true
  tasks:

  - name: Install Apache and PHP 
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
